server:
  port:8080

# H2 In-Memory Database Configuration for Tests
spring:
  datasource:
#    url: "jdbc:h2:mem:test-db"
#    driverClassName: "org.h2.Driver"
#    username: "sa"
#    password: "password"
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  #h2.console.enabled: true

  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always



app:
  doc:
    version: 2023-Fall
    title: SE352-452 Library Management test environment
    description: This is documentation for library management system for SE352-452
    terms: http://swagger.io/terms/
    license:  Apache 2.0
    url: http://springdoc.org
